export const PRODUCT_OPTIONS: Record<string, Record<string, any>> = {
  IPHONES_SAMSUNG: {
    brand: [
      'Apple', 'Samsung', 'Xiaomi', 'Huawei', 'Tecno', 'Infinix',
      'Oppo', 'Vivo', 'Realme', 'Nothing', 'Google', 'OnePlus',
    ],
    model: {
      Apple: [
        'iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 16 Plus', 'iPhone 16',
        'iPhone 15 Pro Max', 'iPhone 15 Pro', 'iPhone 15 Plus', 'iPhone 15',
        'iPhone 14 Pro Max', 'iPhone 14 Pro', 'iPhone 14', 'iPhone 13 Pro Max',
        'iPhone 13 Pro', 'iPhone 13', 'iPhone 13 Mini', 'iPhone 12 Pro Max',
        'iPhone 12 Pro', 'iPhone 12', 'iPhone 12 Mini', 'iPhone SE (3rd Gen)',
        'iPhone 11 Pro Max', 'iPhone 11 Pro', 'iPhone 11', 'iPhone XR', 'iPhone XS Max',
      ],
      Samsung: [
        'Galaxy S25 Ultra', 'Galaxy S25+', 'Galaxy S25', 'Galaxy S24 Ultra', 'Galaxy S24+',
        'Galaxy S24', 'Galaxy S23 Ultra', 'Galaxy S23+', 'Galaxy S23',
        'Galaxy S22 Ultra', 'Galaxy S22+', 'Galaxy S22', 'Galaxy S21 FE',
        'Galaxy A56', 'Galaxy A55', 'Galaxy A36', 'Galaxy A35', 'Galaxy A26',
        'Galaxy A16', 'Galaxy A06', 'Galaxy A05s', 'Galaxy A05',
        'Galaxy Z Fold6', 'Galaxy Z Flip6', 'Galaxy Z Fold5', 'Galaxy Z Flip5',
        'Galaxy Note 20 Ultra', 'Galaxy Note 20',
      ],
      Xiaomi: [
        'Redmi Note 14 Pro+', 'Redmi Note 14 Pro', 'Redmi Note 14',
        'Redmi 14C', 'Redmi 13', 'Redmi 13C', 'Redmi 12',
        'POCO X7 Pro', 'POCO X7', 'POCO F6 Pro', 'POCO F6',
        'POCO M7 Pro', 'POCO M7', 'POCO C75',
        'Xiaomi 15 Ultra', 'Xiaomi 15 Pro', 'Xiaomi 15',
        'Xiaomi 14 Ultra', 'Xiaomi 14 Pro', 'Xiaomi 14',
      ],
      Huawei: [
        'Pura 70 Ultra', 'Pura 70 Pro+', 'Pura 70 Pro', 'Pura 70',
        'Mate 60 Pro+', 'Mate 60 Pro', 'Mate 60',
        'Nova 12 Pro', 'Nova 12', 'Nova Y91', 'Nova Y72',
        'Enjoy 70 Pro', 'Enjoy 70',
      ],
      Tecno: [
        'Phantom V Fold2', 'Phantom V Flip2', 'Phantom X2 Pro',
        'Camon 30 Pro', 'Camon 30', 'Camon 30S Pro', 'Camon 30S',
        'Camon 20 Pro', 'Camon 20', 'Pop 8', 'Pop 7 Pro', 'Pop 7',
        'Spark 20 Pro+', 'Spark 20 Pro', 'Spark 20C', 'Spark 20',
        'Pova 6 Pro', 'Pova 6', 'Pova 5 Pro', 'Pova 5',
      ],
      Infinix: [
        'Zero 40', 'Zero 40 5G', 'Zero 30', 'Zero 30 5G',
        'Hot 50 Pro+', 'Hot 50 Pro', 'Hot 50i', 'Hot 50',
        'Hot 40 Pro', 'Hot 40', 'Hot 40i', 'Hot 40 Play',
        'Note 40 Pro+', 'Note 40 Pro', 'Note 40', 'Note 30 Pro', 'Note 30',
        'Smart 9', 'Smart 8 Pro', 'Smart 8',
      ],
      Oppo: [
        'Find X8 Pro', 'Find X8', 'Find X7 Ultra', 'Find X7',
        'Reno 12 Pro', 'Reno 12', 'Reno 11F', 'Reno 11 Pro', 'Reno 11',
        'A3 Pro', 'A3', 'A2 Pro', 'A2', 'A1x', 'A1 Pro', 'A1',
        'Find N3 Flip', 'Find N3',
      ],
      Vivo: [
        'X200 Pro', 'X200', 'X100 Pro', 'X100',
        'V40 SE', 'V40 Lite', 'V40', 'V30 SE', 'V30 Lite', 'V30 Pro', 'V30',
        'Y28', 'Y27', 'Y26', 'Y25', 'Y18', 'Y17s', 'Y16',
      ],
      Realme: [
        'GT 7 Pro', 'GT 6', 'GT 5 Pro', 'GT 5',
        '13 Pro+', '13 Pro', '13', '12 Pro+', '12 Pro', '12', '12x',
        'Narzo 70x', 'Narzo 70 Pro', 'Narzo 70', 'Narzo N61', 'Narzo N60',
        'C67', 'C65', 'C61', 'C55', 'C53', 'C51', 'C50',
      ],
      Nothing: [
        'Phone (2a) Plus', 'Phone (2a)', 'Phone (2)', 'Phone (1)',
      ],
      Google: [
        'Pixel 9 Pro Fold', 'Pixel 9 Pro XL', 'Pixel 9 Pro', 'Pixel 9',
        'Pixel 8a', 'Pixel 8 Pro', 'Pixel 8', 'Pixel 7a', 'Pixel 7 Pro', 'Pixel 7',
      ],
      OnePlus: [
        '13', '12R', '12', 'Open', 'Nord CE4 Lite', 'Nord CE4', 'Nord 3',
      ],
    },
    storage: ['32GB', '64GB', '128GB', '256GB', '512GB', '1TB'],
    ram: ['3GB', '4GB', '6GB', '8GB', '12GB', '16GB'],
    color: [
      'Black', 'White', 'Silver', 'Gold', 'Blue', 'Green', 'Purple', 'Red',
      'Pink', 'Yellow', 'Orange', 'Natural Titanium', 'Blue Titanium',
      'White Titanium', 'Black Titanium', 'Desert Titanium',
      'Midnight', 'Starlight', 'Space Gray', 'Graphite',
      'Sky Blue', 'Lavender', 'Mint', 'Cream', 'Phantom Black',
    ],
    condition: ['Brand New', 'Used - Like New', 'Used - Good', 'Used - Fair'],
    carrier: ['Unlocked', 'AT&T', 'T-Mobile', 'Verizon', 'Safaricom', 'Ethio Telecom', 'Other'],
  },

  IPADS_MACBOOKS: {
    brand: ['Apple'],
    model: {
      Apple: [
        'iPad Pro M4 13"', 'iPad Pro M4 11"', 'iPad Pro M2 12.9"', 'iPad Pro M2 11"',
        'iPad Air M2 13"', 'iPad Air M2 11"', 'iPad Air M1',
        'iPad 10th Gen', 'iPad 9th Gen', 'iPad Mini 6th Gen',
        'MacBook Pro M4 Max 16"', 'MacBook Pro M4 Pro 16"', 'MacBook Pro M4 14"',
        'MacBook Pro M4 Pro 14"', 'MacBook Pro M3 Pro 14"', 'MacBook Pro M3 14"',
        'MacBook Pro M3 Max 16"', 'MacBook Pro M3 Pro 16"',
        'MacBook Air M3 15"', 'MacBook Air M3 13"', 'MacBook Air M2 15"', 'MacBook Air M2 13"',
        'MacBook Air M1 13"',
      ],
    },
    storage: ['64GB', '128GB', '256GB', '512GB', '1TB', '2TB'],
    ram: ['8GB', '16GB', '24GB', '32GB', '36GB', '48GB'],
    color: [
      'Space Black', 'Silver', 'Starlight', 'Midnight', 'Space Gray',
      'Natural', 'Blue', 'Purple', 'Pink',
    ],
    condition: ['Brand New', 'Used - Like New', 'Used - Good', 'Used - Fair'],
    screenSize: ['10.2"', '10.9"', '11"', '12.9"', '13.3"', '13.6"', '14.2"', '15.3"', '16.2"'],
    processor: ['M1', 'M2', 'M3', 'M4', 'M3 Pro', 'M3 Max', 'M4 Pro', 'M4 Max'],
    connectivity: ['Wi-Fi Only', 'Wi-Fi + Cellular'],
  },

  LAPTOPS: {
    brand: [
      'Apple', 'HP', 'Dell', 'Lenovo', 'Asus', 'Acer', 'Microsoft',
      'MSI', 'Razer', 'Samsung', 'Huawei',
    ],
    model: {
      Apple: [
        'MacBook Pro M4 Max 16"', 'MacBook Pro M4 Pro 16"', 'MacBook Pro M4 14"',
        'MacBook Pro M4 Pro 14"', 'MacBook Pro M3 Pro 14"', 'MacBook Pro M3 14"',
        'MacBook Air M3 15"', 'MacBook Air M3 13"', 'MacBook Air M2 15"', 'MacBook Air M2 13"',
      ],
      HP: [
        'Spectre x360 14', 'Spectre x360 16', 'Envy 16', 'Envy x360 15',
        'Pavilion 15', 'Pavilion Plus 14', 'Victus 16', 'Victus 15',
        'ProBook 450 G10', 'ProBook 440 G10', 'EliteBook 840 G10',
        'ZBook Fury 16 G10',
      ],
      Dell: [
        'XPS 16', 'XPS 15', 'XPS 14', 'XPS 13 Plus', 'XPS 13',
        'Inspiron 16', 'Inspiron 15', 'Inspiron 14', 'Inspiron 7',
        'Latitude 7440', 'Latitude 5540', 'Latitude 5440',
        'Precision 5680', 'Precision 7680',
        'Alienware m18 R2', 'Alienware x16 R2', 'Alienware m16 R2',
      ],
      Lenovo: [
        'ThinkPad X1 Carbon Gen 12', 'ThinkPad X1 Yoga Gen 8',
        'ThinkPad T14s Gen 4', 'ThinkPad T14 Gen 5', 'ThinkPad T16 Gen 2',
        'ThinkPad E16 Gen 2', 'ThinkPad E14 Gen 6',
        'IdeaPad Slim 5 14', 'IdeaPad Slim 5 16', 'IdeaPad Gaming 3 15',
        'Yoga 9i 14', 'Yoga 7i 14', 'Yoga 7i 16',
        'Legion Pro 7i 16', 'Legion Pro 5i 16', 'Legion Slim 5 14',
        'LOQ 15IRX9', 'LOQ 15IAX9',
      ],
      Asus: [
        'ROG Strix SCAR 18', 'ROG Strix SCAR 16', 'ROG Strix G18', 'ROG Strix G16',
        'ROG Zephyrus G16', 'ROG Zephyrus G14',
        'Zenbook 14 OLED', 'Zenbook S 13 OLED', 'Zenbook Pro 16X OLED',
        'Vivobook S 15 OLED', 'Vivobook S 14 OLED', 'Vivobook 15', 'Vivobook 14',
        'TUF Gaming A15', 'TUF Gaming A16', 'TUF Gaming F15', 'TUF Gaming F16',
      ],
      Acer: [
        'Predator Helios 18', 'Predator Helios 16', 'Predator Helios Neo 16',
        'Nitro V 15', 'Nitro 5', 'Nitro 16',
        'Aspire 5', 'Aspire 7', 'Aspire Lite',
        'Swift Go 14', 'Swift 3',
      ],
      Microsoft: [
        'Surface Laptop 7 15"', 'Surface Laptop 7 13.8"', 'Surface Laptop 6 15"',
        'Surface Laptop 6 13.5"', 'Surface Laptop Go 3',
        'Surface Pro 11', 'Surface Pro 10',
      ],
      MSI: [
        'Raider GE78 HX', 'Raider GE68 HX', 'Stealth 18 AI Studio',
        'Stealth 16 AI Studio', 'Creator Z17 HX Studio',
        'Cyborg 15', 'Thin 15', 'GF63 Thin',
      ],
      Razer: [
        'Blade 18', 'Blade 16', 'Blade 15', 'Blade 14',
      ],
      Samsung: [
        'Galaxy Book4 Ultra', 'Galaxy Book4 Pro 360', 'Galaxy Book4 Pro',
        'Galaxy Book4', 'Galaxy Book3 360', 'Galaxy Book3 Pro',
      ],
      Huawei: [
        'MateBook X Pro', 'MateBook 16s', 'MateBook 14s', 'MateBook D 16',
        'MateBook D 14',
      ],
    },
    processor: [
      'Intel Core i5', 'Intel Core i7', 'Intel Core i9', 'Intel Core Ultra 5',
      'Intel Core Ultra 7', 'Intel Core Ultra 9',
      'AMD Ryzen 5', 'AMD Ryzen 7', 'AMD Ryzen 9',
      'Apple M1', 'Apple M2', 'Apple M3', 'Apple M4',
      'Apple M3 Pro', 'Apple M3 Max', 'Apple M4 Pro', 'Apple M4 Max',
    ],
    ram: ['4GB', '8GB', '16GB', '32GB', '64GB'],
    storage: ['128GB SSD', '256GB SSD', '512GB SSD', '1TB SSD', '1TB HDD', '2TB SSD'],
    storageType: ['SSD', 'HDD', 'NVMe', 'eMMC'],
    gpu: [
      'Intel UHD', 'Intel Iris Xe', 'Intel Arc',
      'NVIDIA RTX 4050 6GB', 'NVIDIA RTX 4060 8GB', 'NVIDIA RTX 4070 8GB',
      'NVIDIA RTX 4070 12GB', 'NVIDIA RTX 4080 12GB', 'NVIDIA RTX 4090 16GB',
      'NVIDIA RTX 3050 4GB', 'NVIDIA RTX 3050 6GB',
      'NVIDIA RTX 3060 6GB', 'NVIDIA RTX 3060 12GB',
      'NVIDIA RTX 3070 8GB', 'NVIDIA RTX 3080 10GB', 'NVIDIA RTX 3080 16GB',
      'NVIDIA GeForce MX550', 'NVIDIA GeForce MX450',
      'AMD Radeon Graphics', 'AMD Radeon RX 6600M', 'AMD Radeon RX 6800M',
      'AMD Radeon 780M', 'AMD Radeon 680M',
      'Apple M1 GPU', 'Apple M2 GPU', 'Apple M3 GPU', 'Apple M4 GPU',
    ],
    screenSize: ['13.3"', '14"', '15.6"', '16"', '17.3"'],
    color: [
      'Black', 'Silver', 'White', 'Gray', 'Blue', 'Green',
      'Space Gray', 'Midnight', 'Starlight', 'Gunmetal', 'Platinum',
    ],
    condition: ['Brand New', 'Used - Like New', 'Used - Good', 'Used - Fair'],
    os: ['Windows 10', 'Windows 11', 'macOS', 'Linux', 'ChromeOS'],
  },

  AIRPODS: {
    brand: ['Apple'],
    model: [
      'AirPods 4', 'AirPods 4 (ANC)',
      'AirPods Pro 2 (USB-C)', 'AirPods Pro 2 (Lightning)',
      'AirPods Pro 1', 'AirPods 3rd Gen', 'AirPods 2nd Gen',
      'AirPods Max (USB-C)', 'AirPods Max (Lightning)',
    ],
    color: ['White', 'Silver', 'Space Gray', 'Sky Blue', 'Green', 'Pink', 'Orange', 'Purple'],
    condition: ['Brand New', 'Used - Like New', 'Used - Good', 'Used - Fair'],
  },

  SMARTWATCHES: {
    brand: ['Apple', 'Samsung', 'Huawei', 'Xiaomi', 'Amazfit', 'Garmin'],
    model: {
      Apple: [
        'Apple Watch Ultra 2', 'Apple Watch Ultra',
        'Apple Watch Series 10 46mm', 'Apple Watch Series 10 42mm',
        'Apple Watch Series 9 45mm', 'Apple Watch Series 9 41mm',
        'Apple Watch SE 2nd Gen 44mm', 'Apple Watch SE 2nd Gen 40mm',
      ],
      Samsung: [
        'Galaxy Watch Ultra', 'Galaxy Watch7 44mm', 'Galaxy Watch7 40mm',
        'Galaxy Watch6 Classic 47mm', 'Galaxy Watch6 Classic 43mm',
        'Galaxy Watch6 44mm', 'Galaxy Watch6 40mm',
        'Galaxy Watch FE', 'Galaxy Watch5 Pro', 'Galaxy Watch5 44mm', 'Galaxy Watch5 40mm',
        'Galaxy Watch4 Classic 46mm', 'Galaxy Watch4 Classic 42mm',
        'Galaxy Watch4 44mm', 'Galaxy Watch4 40mm',
      ],
      Huawei: [
        'Watch GT 5 Pro 46mm', 'Watch GT 5 Pro 42mm',
        'Watch GT 5 46mm', 'Watch GT 5 41mm',
        'Watch GT 4 46mm', 'Watch GT 4 41mm',
        'Watch GT 3 Pro 46mm', 'Watch GT 3 Pro 43mm',
        'Watch Fit 3', 'Watch Fit SE', 'Watch D2',
      ],
      Xiaomi: [
        'Watch S4', 'Watch S3', 'Watch S2', 'Watch S1',
        'Redmi Watch 5', 'Redmi Watch 4', 'Redmi Watch 3 Active',
        'Smart Band 9 Pro', 'Smart Band 9',
      ],
      Amazfit: [
        'T-Rex Ultra', 'T-Rex 3', 'T-Rex 2',
        'GTR 4', 'GTR 3 Pro', 'GTR 3',
        'GTS 4 Mini', 'GTS 4', 'GTS 3',
        'Active 2', 'Active',
      ],
      Garmin: [
        'Fenix 8', 'Fenix 7X', 'Fenix 7', 'Fenix 6',
        'Forerunner 965', 'Forerunner 265', 'Forerunner 165',
        'Venu 3', 'Venu 2', 'Vivoactive 5',
        'Instinct 2X', 'Instinct 2',
      ],
    },
    caseSize: ['38mm', '40mm', '41mm', '42mm', '44mm', '45mm', '46mm', '49mm'],
    color: [
      'Black', 'Silver', 'White', 'Gold', 'Rose Gold', 'Blue', 'Green',
      'Titanium', 'Natural', 'Midnight', 'Starlight', 'Orange',
      'Pink Gold', 'Graphite',
    ],
    connectivity: ['Wi-Fi Only', 'Wi-Fi + Cellular', 'Bluetooth Only'],
    storage: ['32GB', '64GB', '128GB', '256GB', '32GB eMMC'],
    condition: ['Brand New', 'Used - Like New', 'Used - Good', 'Used - Fair'],
  },
};

export const FIELD_LABELS: Record<string, string> = {
  brand: 'Brand',
  model: 'Model',
  storage: 'Storage',
  ram: 'RAM',
  color: 'Color',
  condition: 'Condition',
  processor: 'Processor',
  gpu: 'GPU',
  screenSize: 'Screen Size',
  os: 'OS',
  batteryHealth: 'Battery Health',
  carrier: 'Carrier',
  caseSize: 'Case Size',
  connectivity: 'Connectivity',
  hasWarranty: 'Warranty',
  hasAppleCare: 'AppleCare',
  year: 'Year',
  storageType: 'Storage Type',
};
