export const DEFAULT_CATEGORIES = [
  {
    name: 'IPHONES_SAMSUNG',
    displayName: "iPhones & Samsung's",
    icon: 'smartphone',
    schemaRules: [
      { field: 'brand', type: 'string', required: true },
      { field: 'model', type: 'string', required: true },
      { field: 'storage', type: 'select', required: true, options: ['64GB', '128GB', '256GB', '512GB', '1TB'] },
      { field: 'ram', type: 'select', options: ['3GB', '4GB', '6GB', '8GB', '12GB', '16GB'] },
      { field: 'color', type: 'string', required: true },
      { field: 'year', type: 'number' },
      { field: 'batteryHealth', type: 'string' },
      { field: 'carrier', type: 'select', options: ['Unlocked', 'AT&T', 'T-Mobile', 'Verizon', 'Other'] },
      { field: 'hasWarranty', type: 'boolean' },
    ],
  },
  {
    name: 'IPADS_MACBOOKS',
    displayName: 'iPads / MacBooks',
    icon: 'tablet',
    schemaRules: [
      { field: 'brand', type: 'string', required: true },
      { field: 'model', type: 'string', required: true },
      { field: 'storage', type: 'select', required: true, options: ['64GB', '128GB', '256GB', '512GB', '1TB', '2TB'] },
      { field: 'ram', type: 'select', options: ['8GB', '16GB', '24GB', '32GB', '36GB', '48GB'] },
      { field: 'color', type: 'string', required: true },
      { field: 'screenSize', type: 'select', options: ['10.2"', '10.9"', '11"', '12.9"', '13.3"', '13.6"', '14.2"', '15.3"', '16.2"'] },
      { field: 'processor', type: 'select', options: ['M1', 'M2', 'M3', 'M4', 'Intel Core i5', 'Intel Core i7', 'Intel Core i9'] },
      { field: 'connectivity', type: 'select', options: ['Wi-Fi Only', 'Wi-Fi + Cellular'] },
      { field: 'hasWarranty', type: 'boolean' },
    ],
  },
  {
    name: 'LAPTOPS',
    displayName: 'Laptops',
    icon: 'laptop',
    schemaRules: [
      { field: 'brand', type: 'string', required: true },
      { field: 'model', type: 'string', required: true },
      { field: 'processor', type: 'string', required: true },
      { field: 'ram', type: 'select', required: true, options: ['4GB', '8GB', '16GB', '32GB', '64GB'] },
      { field: 'storage', type: 'select', required: true, options: ['128GB SSD', '256GB SSD', '512GB SSD', '1TB SSD', '1TB HDD', '2TB SSD'] },
      { field: 'storageType', type: 'select', options: ['SSD', 'HDD', 'NVMe', 'eMMC'] },
      { field: 'gpu', type: 'string' },
      { field: 'screenSize', type: 'select', options: ['13.3"', '14"', '15.6"', '16"', '17.3"'] },
      { field: 'color', type: 'string' },
      { field: 'generation', type: 'string' },
      { field: 'os', type: 'select', options: ['Windows 10', 'Windows 11', 'macOS', 'Linux', 'ChromeOS'] },
      { field: 'hasWarranty', type: 'boolean' },
    ],
  },
  {
    name: 'AIRPODS',
    displayName: 'AirPods',
    icon: 'headphones',
    schemaRules: [
      { field: 'brand', type: 'string', required: true },
      { field: 'model', type: 'select', required: true, options: ['AirPods (3rd Gen)', 'AirPods Pro (1st Gen)', 'AirPods Pro (2nd Gen)', 'AirPods Pro (2nd Gen, USB-C)', 'AirPods Max (Lightning)', 'AirPods Max (USB-C)'] },
      { field: 'color', type: 'select', options: ['White', 'Silver', 'Space Gray', 'Sky Blue', 'Green', 'Pink'] },
      { field: 'hasWarranty', type: 'boolean' },
      { field: 'hasAppleCare', type: 'boolean' },
    ],
  },
  {
    name: 'SMARTWATCHES',
    displayName: "Smartwatch's",
    icon: 'watch',
    schemaRules: [
      { field: 'brand', type: 'string', required: true },
      { field: 'model', type: 'string', required: true },
      { field: 'storage', type: 'select', options: ['32GB', '64GB', '128GB', '256GB', '32GB eMMC'] },
      { field: 'caseSize', type: 'select', options: ['38mm', '40mm', '41mm', '42mm', '44mm', '45mm', '46mm', '49mm'] },
      { field: 'color', type: 'string' },
      { field: 'connectivity', type: 'select', options: ['Wi-Fi Only', 'Wi-Fi + Cellular', 'Bluetooth Only'] },
      { field: 'hasWarranty', type: 'boolean' },
    ],
  },
];
